### ISSUE TITLE
demo.cpp build failed on linux mint 20.3 with cmake 3.24.1

### ISSUE THREAD

**Issue by erusyd** [Blake-Madden/Wisteria-Dataviz#16]
![image](https://user-images.githubusercontent.com/1529102/191928328-c51b0f95-493d-4d6a-954b-96a17ae20065.png)

I use wxWidgets 3.2.1 from CodeLite PPA.

Build steps:
1. mkdir build
2. cd build
3. cmake ..
4. make -j$(nproc)

**Comment by Blake-Madden** [comment]
Should be fixed now.  Can you please try again with the latest update.

**Comment by erusyd** [comment]
> Should be fixed now. Can you please try again with the latest update.

I try the latest update, it compiles with the following error:

 [ 96%] Built target Wisteria
Consolidate compiler generated dependencies of target WisteriaDemo
[ 98%] Linking CXX executable WisteriaDemo
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `void tbb::interface7::internal::isolate_impl<void, __pstl::__par_backend::__parallel_stable_sort<__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, __pstl::__internal::__pattern_sort<__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false> >(__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false>, std::integral_constant<bool, true>, std::integral_constant<bool, true>)::{lambda()#1}::operator()() const::{lambda(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>)#1}>(__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, __pstl::__internal::__pattern_sort<__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false> >(__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false>, std::integral_constant<bool, true>, std::integral_constant<bool, true>)::{lambda()#1}::operator()() const::{lambda(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>)#1}, unsigned long)::{lambda()#1} const>(__pstl::__par_backend::__parallel_stable_sort<__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, __pstl::__internal::__pattern_sort<__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false> >(__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false>, std::integral_constant<bool, true>, std::integral_constant<bool, true>)::{lambda()#1}::operator()() const::{lambda(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>)#1}>(__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, __pstl::__internal::__pattern_sort<__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false> >(__pstl::execution::v1::parallel_policy const&, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>, std::integral_constant<bool, false>, std::integral_constant<bool, true>, std::integral_constant<bool, true>)::{lambda()#1}::operator()() const::{lambda(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::less<double>)#1}, unsigned long)::{lambda()#1} const&)':
/usr/include/tbb/task_arena.h:216: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `tbb::tbb_allocator<double>::allocate(unsigned long, void const*)':
/usr/include/tbb/tbb_allocator.h:86: undefined reference to `tbb::internal::allocate_via_handler_v3(unsigned long)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `operator new(unsigned long, tbb::internal::allocate_root_proxy const&)':
/usr/include/tbb/task.h:1134: undefined reference to `tbb::internal::allocate_root_proxy::allocate(unsigned long)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `tbb::tbb_allocator<double>::deallocate(double*, unsigned long)':
/usr/include/tbb/tbb_allocator.h:91: undefined reference to `tbb::internal::deallocate_via_handler_v3(void*)'
/usr/bin/ld: /usr/include/tbb/tbb_allocator.h:91: undefined reference to `tbb::internal::deallocate_via_handler_v3(void*)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `operator new(unsigned long, tbb::internal::allocate_continuation_proxy const&)':
/usr/include/tbb/task.h:1152: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `operator new(unsigned long, tbb::internal::allocate_child_proxy const&)':
/usr/include/tbb/task.h:1160: undefined reference to `tbb::internal::allocate_child_proxy::allocate(unsigned long) const'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `operator new(unsigned long, tbb::internal::allocate_continuation_proxy const&)':
/usr/include/tbb/task.h:1152: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
/usr/bin/ld: /usr/include/tbb/task.h:1152: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o): in function `operator new(unsigned long, tbb::internal::allocate_additional_child_of_proxy const&)':
/usr/include/tbb/task.h:1168: undefined reference to `tbb::internal::allocate_additional_child_of_proxy::allocate(unsigned long) const'
/usr/bin/ld: /usr/include/tbb/task.h:1168: undefined reference to `tbb::internal::allocate_additional_child_of_proxy::allocate(unsigned long) const'
/usr/bin/ld: /usr/include/tbb/task.h:1168: undefined reference to `tbb::internal::allocate_additional_child_of_proxy::allocate(unsigned long) const'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTIN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_16__serial_destroyENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE[_ZTIN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_16__serial_destroyENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE]+0x10): undefined reference to `typeinfo for tbb::task'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTIN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE[_ZTIN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE]+0x10): undefined reference to `typeinfo for tbb::task'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTIN6__pstl13__par_backend12__merge_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES8_S4_St4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S4_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS8_S4_E1_ZNSV_7executeEvEUlS8_S8_S4_E2_EEEE[_ZTIN6__pstl13__par_backend12__merge_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES8_S4_St4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S4_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS8_S4_E1_ZNSV_7executeEvEUlS8_S8_S4_E2_EEEE]+0x10): undefined reference to `typeinfo for tbb::task'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTVN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_16__serial_destroyENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE[_ZTVN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_16__serial_destroyENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE]+0x28): undefined reference to `tbb::task::note_affinity(unsigned short)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTVN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE[_ZTVN6__pstl13__par_backend12__merge_taskIPdS2_N9__gnu_cxx17__normal_iteratorIS2_St6vectorIdSaIdEEEESt4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S2_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS2_S8_E_ZNSV_7executeEvEUlS2_S2_S8_E0_EEEE]+0x28): undefined reference to `tbb::task::note_affinity(unsigned short)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTVN6__pstl13__par_backend12__merge_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES8_S4_St4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S4_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS8_S4_E1_ZNSV_7executeEvEUlS8_S8_S4_E2_EEEE[_ZTVN6__pstl13__par_backend12__merge_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES8_S4_St4lessIdENS0_14__binary_no_opENS0_19__serial_move_mergeIZNS0_18__stable_sort_taskIS8_S4_SA_ZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SP_T1_T2_SL_IbLb1EESS_ENKUlvE_clEvEUlS8_S8_SA_E_E7executeEvEUlS8_S4_E1_ZNSV_7executeEvEUlS8_S8_S4_E2_EEEE]+0x28): undefined reference to `tbb::task::note_affinity(unsigned short)'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTIN6__pstl13__par_backend18__stable_sort_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES4_St4lessIdEZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SM_T1_T2_SI_IbLb1EESP_ENKUlvE_clEvEUlS8_S8_SA_E_EE[_ZTIN6__pstl13__par_backend18__stable_sort_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES4_St4lessIdEZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SM_T1_T2_SI_IbLb1EESP_ENKUlvE_clEvEUlS8_S8_SA_E_EE]+0x10): undefined reference to `typeinfo for tbb::task'
/usr/bin/ld: libWisteria.a(boxplot.cpp.o):(.data.rel.ro._ZTVN6__pstl13__par_backend18__stable_sort_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES4_St4lessIdEZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SM_T1_T2_SI_IbLb1EESP_ENKUlvE_clEvEUlS8_S8_SA_E_EE[_ZTVN6__pstl13__par_backend18__stable_sort_taskIN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEES4_St4lessIdEZZNS_10__internal14__pattern_sortIRKNS_9execution2v115parallel_policyES8_SA_St17integral_constantIbLb0EEEEvOT_T0_SM_T1_T2_SI_IbLb1EESP_ENKUlvE_clEvEUlS8_S8_SA_E_EE]+0x28): undefined reference to `tbb::task::note_affinity(unsigned short)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/WisteriaDemo.dir/build.make:98: WisteriaDemo] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/WisteriaDemo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

It seems that we should link with tbb library, i.e. add -ltbb.

**Comment by erusyd** [comment]
I add following to CMakeLists.txt:
![image](https://user-images.githubusercontent.com/1529102/191965226-1dd282d9-90f2-4455-ae15-3f446157b800.png)

It compiles OK, but when I run the Demo:
![image](https://user-images.githubusercontent.com/1529102/191965331-72f2681e-2c78-4ad0-84dd-14fe8a72e2c1.png)

**Comment by Blake-Madden** [comment]
I added libtbb for UNIX builds in the CMake file; thanks for the fix!

I fixed the color issues, the asserts should all be gone now.

**Comment by erusyd** [comment]
It compiles OK now. It runs with some GTK assertion warnings:

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.345: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.346: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.347: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.347: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.347: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.347: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.348: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.348: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.348: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.348: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.349: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.349: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.349: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.349: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.349: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.349: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.349: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.349: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.349: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.349: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.350: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.350: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.352: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.352: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.352: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.352: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.352: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.352: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.352: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.352: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.353: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.353: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.353: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.353: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.354: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.354: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.354: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.354: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.356: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.356: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.358: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.358: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.359: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.359: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.359: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.359: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.359: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.359: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.359: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.359: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.359: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.359: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(WisteriaDemo:2847): GLib-GObject-WARNING **: 19:07:27.360: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(WisteriaDemo:2847): Gtk-CRITICAL **: 19:07:27.360: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

**Comment by Blake-Madden** [comment]
Sorry about the asserts.  I'm on OpenSUSE 32-bit at the moment and not getting these asserts, but I'll try to get a Cinnamon 64-bit to test on ASAP.  Anyway, I did see an open issue in wxWidgets about SVGs under GTK, might be related maybe.  I've removed the menu icons from the sample for now to at least get rid of the asserts.
