### ISSUE TITLE
Bugs in sample when importing CSV

### ISSUE THREAD

**Issue by PBfordev** [Blake-Madden/Wisteria-Dataviz#3]
Please, if you are not accepting issues, let me know and I will stop submitting them. It's just wxWidgets is in a sore need of a good maintained chart library, so I took interest in yours, thanks for it BTW.

**Bug 1**
The sample imports its files like this `pieData->ImportCSV(L"datasets/Fall Enrollment.csv"...`

However, relying on the CWD means that the import fails when the sample is launched from MSVS. Therefore, the sample should for example use `wxStandardPaths::GetResourcesDir()` and `wxFileName` to compose the path relative to the executable.

**Bug 2**
Reporting import error shows two error boxes: one empty followed by one by `wxLogError()`. When `Dataset::ImportText()` encounters an error when opening/reading the file, it throws `std::runtime_error`, passing it a `wxString` which includes the system error message. However, standard exception uses narrow `std::string`, so when the system error message contains characters not representable in the current code page, `wxString` conversion to narrow char produces an empty string:
![wisteria-demo-error-empty](https://user-images.githubusercontent.com/12495521/166809563-1aef1385-e83d-4362-ad63-cfbcf75f5b19.png)
As the wxWidgets built-in error reporting mechanism was not suppressed with `wxLogNull` when using `wxTextFile`, another error box is produced:
![wisteria-demo-logerror](https://user-images.githubusercontent.com/12495521/166809766-31782053-0af5-49bd-ad56-415c8d1d8070.png)

**Comment by Blake-Madden** [comment]
Yes, I am absolutely accepting issues and thanks for trying out the library! I definitely plan on maintaining it for a long time, I heavily use it for some other projects that I work on.

I'll check these issue out tonight...

**Comment by Blake-Madden** [comment]
For bug 2, I think handling exception::what as UTF-8 will fix it.  I'll test that...

**Comment by Blake-Madden** [comment]
For the second part of bug 2, IMO the log message is OK. Failing to open a file is major problem and I think it's OK to allow the framework to log that, rather than me arbitrarily burying it.  If I bury that log message, then it's expected for the developer to show a helpful error message in their catch block explaining what happened.  I hate to make that assumption.

Also, there is a snazzy `LogFile` class included in the library to route these message to a file so that they don't pop out at the client :)

**Comment by Blake-Madden** [comment]
Merged PR #5; also, added UTF-8 logic to exceptions, fixed paths in examples elsewhere.
