### ISSUE TITLE
Any feature about two Y axies in the chart?

### ISSUE THREAD

**Issue by asmwarrior** [Blake-Madden/Wisteria-Dataviz#43]
Hi, I'm not familiar with your library.

I'm using a very simple wxMathPlot library for many years.

Now, I need some new features for 2 Y axis, I mean something like:

[Plots with different scales — Matplotlib 3.8.3 documentation](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/two_scales.html)

Is this possible?

Thanks.

I added a cross reference to wxMathPlot's ticket, it is hard to implement such feature in wxMathPlot library, see : [two y axis with different coordinates, one on left and one on right · Issue #20 · GitHubLionel/wxMathPlot](https://github.com/GitHubLionel/wxMathPlot/issues/20)

**Comment by Blake-Madden** [comment]
I might be able to add something like this, I'll look into it. It certainly would have very practical applications (e.g., Metric vs. Imperial measurements along opposite axes).

**Comment by Blake-Madden** [comment]
OK, so this is possible, but there is a specific way that you must specify the second axis's scale for it to work as expected. Please refer to the updated axes overview topic.

**Comment by asmwarrior** [comment]
Hi, thanks for the quick response and implementation. 

Where can I find the updated axes overview topic?  Oh, it is here:

https://github.com/Blake-Madden/Wisteria-Dataviz/blob/main/Axes.md#dual-axes

I will take some time to build your project and learn how to use this feature.

**Comment by asmwarrior** [comment]
When I looked at the document(markdown file), I see that you use a lot of ascii art like diagram, this is quick nice feature, I also love to use such kinds of diagram in my code. Which tool did you use to create those ascii art like diagram? For me, I use the online version of 
https://asciiflow.com/#/

But I see some one was not satisfied with the online version, so he created his own one(which support either wxWidgets GUI or Qt GUI, see here: https://github.com/schorsch1976/AsciiFlowQT  (Sadly the author of the project is not active for about 9 months, and I have several issues reported in his project.)

**Comment by Blake-Madden** [comment]
I actually did the ASCII art by hand. It was a little tedious, but I think it turned out OK :)
